server {
    listen 80;
    server_name localhost;

    # Thư mục chứa code đã build
    root /usr/share/nginx/html;
    index index.html;

    # Xử lý Router cho AngularJS
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Chặn truy cập các file ẩn
    location ~ /\. {
        deny all;
    }
}